In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

df=pd.read_csv("synthetic_coffee_health_10000.csv")
df.head()

ID  Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
0   1   40    Male  Germany            3.5        328.1          7.5   
1   2   33    Male  Germany            1.0         94.1          6.2   
2   3   42    Male   Brazil            5.3        503.7          5.9   
3   4   53    Male  Germany            2.6        249.2          7.3   
4   5   32  Female    Spain            3.1        298.0          5.3   

  Sleep_Quality   BMI  Heart_Rate Stress_Level  Physical_Activity_Hours  \
0          Good  24.9          78          Low                     14.5   
1          Good  20.0          67          Low                     11.0   
2          Fair  22.7          59       Medium                     11.2   
3          Good  24.7          71          Low                      6.6   
4          Fair  24.1          76       Medium                      8.5   

  Health_Issues Occupation  Smoking  Alcohol_Consumption  
0           NaN      Other        0                    0  
1           NaN    Service        0                    0  
2          Mild     Office        0                    0  
3          Mild      Other        0                    0  
4          Mild    Student        0                    1

In [2]:
df.duplicated().sum()

np.int64(0)

In [3]:
df.shape

(10000, 16)

In [4]:
df["Age"].value_counts()

Age
18    935
34    354
32    352
37    346
35    338
38    325
31    310
30    310
40    308
36    308
39    304
29    294
33    294
27    291
28    285
43    276
41    276
42    274
25    256
24    229
26    225
44    223
23    221
45    213
46    208
47    194
22    194
49    173
21    171
48    166
20    154
50    137
51    133
19    133
52    114
54    103
53     96
55     84
56     58
57     57
59     52
58     41
60     37
61     25
62     23
63     18
64     14
65     14
66     13
70      8
67      8
68      8
72      7
80      2
71      2
73      2
69      2
77      1
75      1
Name: count, dtype: int64

In [5]:
print(df.columns)

Index(['ID', 'Age', 'Gender', 'Country', 'Coffee_Intake', 'Caffeine_mg',
       'Sleep_Hours', 'Sleep_Quality', 'BMI', 'Heart_Rate', 'Stress_Level',
       'Physical_Activity_Hours', 'Health_Issues', 'Occupation', 'Smoking',
       'Alcohol_Consumption'],
      dtype='object')


In [6]:
df=pd.get_dummies(df,columns=["Gender","Country"],drop_first=True,dtype=int)

In [7]:
df.dtypes

ID                           int64
Age                          int64
Coffee_Intake              float64
Caffeine_mg                float64
Sleep_Hours                float64
Sleep_Quality               object
BMI                        float64
Heart_Rate                   int64
Stress_Level                object
Physical_Activity_Hours    float64
Health_Issues               object
Occupation                  object
Smoking                      int64
Alcohol_Consumption          int64
Gender_Male                  int64
Gender_Other                 int64
Country_Belgium              int64
Country_Brazil               int64
Country_Canada               int64
Country_China                int64
Country_Finland              int64
Country_France               int64
Country_Germany              int64
Country_India                int64
Country_Italy                int64
Country_Japan                int64
Country_Mexico               int64
Country_Netherlands          int64
Country_Norway      

In [8]:
df

ID  Age  Coffee_Intake  Caffeine_mg  Sleep_Hours Sleep_Quality   BMI  \
0         1   40            3.5        328.1          7.5          Good  24.9   
1         2   33            1.0         94.1          6.2          Good  20.0   
2         3   42            5.3        503.7          5.9          Fair  22.7   
3         4   53            2.6        249.2          7.3          Good  24.7   
4         5   32            3.1        298.0          5.3          Fair  24.1   
...     ...  ...            ...          ...          ...           ...   ...   
9995   9996   50            2.1        199.8          6.0          Fair  30.5   
9996   9997   18            3.4        319.2          5.8          Fair  19.1   
9997   9998   26            1.6        153.4          7.1          Good  25.1   
9998   9999   40            3.4        327.1          7.0          Good  19.3   
9999  10000   42            2.9        277.5          6.4          Good  28.1   

      Heart_Rate Stress_Level  Physical_Activity_Hours  ... Country_Japan  \
0             78          Low                     14.5  ...             0   
1             67          Low                     11.0  ...             0   
2             59       Medium                     11.2  ...             0   
3             71          Low                      6.6  ...             0   
4             76       Medium                      8.5  ...             0   
...          ...          ...                      ...  ...           ...   
9995          50       Medium                     10.1  ...             1   
9996          71       Medium                     11.6  ...             0   
9997          66          Low                     13.7  ...             0   
9998          80          Low                      0.1  ...             0   
9999          72          Low                      9.8  ...             0   

     Country_Mexico  Country_Netherlands  Country_Norway  Country_South Korea  \
0                 0                    0               0                    0   
1                 0                    0               0                    0   
2                 0                    0               0                    0   
3                 0                    0               0                    0   
4                 0                    0               0                    0   
...             ...                  ...             ...                  ...   
9995              0                    0               0                    0   
9996              0                    0               0                    0   
9997              0                    0               0                    0   
9998              0                    0               0                    0   
9999              0                    0               0                    0   

      Country_Spain  Country_Sweden  Country_Switzerland  Country_UK  \
0                 0               0                    0           0   
1                 0               0                    0           0   
2                 0               0                    0           0   
3                 0               0                    0           0   
4                 1               0                    0           0   
...             ...             ...                  ...         ...   
9995              0               0                    0           0   
9996              0               0                    0           1   
9997              0               0                    0           0   
9998              0               0                    0           0   
9999              0               0                    0           0   

      Country_USA  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
9995            0  
9996            0  
9997            0  
9998            0  
9999            0  

[10000 rows x 35 columns]

In [9]:
df.columns

Index(['ID', 'Age', 'Coffee_Intake', 'Caffeine_mg', 'Sleep_Hours',
       'Sleep_Quality', 'BMI', 'Heart_Rate', 'Stress_Level',
       'Physical_Activity_Hours', 'Health_Issues', 'Occupation', 'Smoking',
       'Alcohol_Consumption', 'Gender_Male', 'Gender_Other', 'Country_Belgium',
       'Country_Brazil', 'Country_Canada', 'Country_China', 'Country_Finland',
       'Country_France', 'Country_Germany', 'Country_India', 'Country_Italy',
       'Country_Japan', 'Country_Mexico', 'Country_Netherlands',
       'Country_Norway', 'Country_South Korea', 'Country_Spain',
       'Country_Sweden', 'Country_Switzerland', 'Country_UK', 'Country_USA'],
      dtype='object')

In [10]:
df["Sleep_Quality"].value_counts()

Sleep_Quality
Good         5637
Fair         2050
Excellent    1352
Poor          961
Name: count, dtype: int64

In [11]:
df["Stress_Level"].value_counts()

Stress_Level
Low       6989
Medium    2050
High       961
Name: count, dtype: int64

In [12]:
x = df.drop(columns=['ID', "Sleep_Quality","Health_Issues","Occupation"])
y = df[ ["Sleep_Quality"]]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [14]:
from sklearn.preprocessing import OrdinalEncoder


enc = OrdinalEncoder(categories=[["Low", "Medium", "High"]])

enc.fit(x_train[["Stress_Level"]])

x_train["Stress_Level"] = enc.transform(x_train[["Stress_Level"]])
x_test["Stress_Level"] = enc.transform(x_test[["Stress_Level"]])

In [15]:
x_train["Stress_Level"]

7216    0.0
433     0.0
4692    0.0
5328    1.0
5397    0.0
       ... 
2501    0.0
5979    0.0
9782    0.0
148     0.0
2320    0.0
Name: Stress_Level, Length: 8000, dtype: float64

In [16]:
x_test["Stress_Level"]

8797    2.0
167     0.0
8888    2.0
7902    1.0
9796    1.0
       ... 
6034    0.0
9854    0.0
8097    1.0
9558    1.0
3781    1.0
Name: Stress_Level, Length: 2000, dtype: float64

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LabelEncoder()

In [18]:
le.classes_

array(['Excellent', 'Fair', 'Good', 'Poor'], dtype=object)

In [19]:
y_train_encoded = le.transform(y_train)
y_test_encoded = le.transform(y_test)

c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)
c:\Users\Admin\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [20]:
y_train_encoded

array([2, 2, 2, ..., 2, 2, 2], shape=(8000,))

In [21]:
y_test_encoded

array([3, 2, 3, ..., 1, 1, 1], shape=(2000,))

In [22]:
print(y_train_encoded.dtype)

int64


In [23]:
print(x_train["Stress_Level"].dtype)

float64


In [26]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
svm_classifier=SVC(kernel="linear",C=1.0,random_state=51)
svm_classifier.fit(x_train_scaled,y_train_encoded)


SVC(kernel='linear', random_state=51)

In [27]:
y_pred=svm_classifier.predict(x_test_scaled)
from sklearn.metrics import accuracy_score,classification_report
print("Accuracy:", accuracy_score(y_test_encoded, y_pred))
print("Classification Report:\n", classification_report(y_test_encoded, y_pred))

Accuracy: 0.9935
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.98      0.98       275
           1       1.00      1.00      1.00       431
           2       0.99      0.99      0.99      1104
           3       1.00      1.00      1.00       190

    accuracy                           0.99      2000
   macro avg       0.99      0.99      0.99      2000
weighted avg       0.99      0.99      0.99      2000



In [28]:
y_pred

array([3, 2, 3, ..., 1, 1, 1], shape=(2000,))

In [29]:
y_pred_encoded = le.inverse_transform(y_pred)
y_pred_encoded

array(['Poor', 'Good', 'Poor', ..., 'Fair', 'Fair', 'Fair'],
      shape=(2000,), dtype=object)

In [30]:
import pickle
model=SVC(kernel="linear")
model.fit(x_train,y_train_encoded)

SVC(kernel='linear')

In [31]:
import pickle

# Save to /kaggle/working/ so it appears in the "Output" tab
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)