In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import numpy as np
import pandas as pd
data=pd.read_csv("synthetic_coffee_health_10000.csv")

In [4]:
data.head()

ID  Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
0   1   40    Male  Germany            3.5        328.1          7.5   
1   2   33    Male  Germany            1.0         94.1          6.2   
2   3   42    Male   Brazil            5.3        503.7          5.9   
3   4   53    Male  Germany            2.6        249.2          7.3   
4   5   32  Female    Spain            3.1        298.0          5.3   

  Sleep_Quality   BMI  Heart_Rate Stress_Level  Physical_Activity_Hours  \
0          Good  24.9          78          Low                     14.5   
1          Good  20.0          67          Low                     11.0   
2          Fair  22.7          59       Medium                     11.2   
3          Good  24.7          71          Low                      6.6   
4          Fair  24.1          76       Medium                      8.5   

  Health_Issues Occupation  Smoking  Alcohol_Consumption  
0           NaN      Other        0                    0  
1           NaN    Service        0                    0  
2          Mild     Office        0                    0  
3          Mild      Other        0                    0  
4          Mild    Student        0                    1

In [5]:
data.tail()

ID  Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
9995   9996   50  Female    Japan            2.1        199.8          6.0   
9996   9997   18  Female       UK            3.4        319.2          5.8   
9997   9998   26    Male    China            1.6        153.4          7.1   
9998   9999   40  Female  Finland            3.4        327.1          7.0   
9999  10000   42  Female   Brazil            2.9        277.5          6.4   

     Sleep_Quality   BMI  Heart_Rate Stress_Level  Physical_Activity_Hours  \
9995          Fair  30.5          50       Medium                     10.1   
9996          Fair  19.1          71       Medium                     11.6   
9997          Good  25.1          66          Low                     13.7   
9998          Good  19.3          80          Low                      0.1   
9999          Good  28.1          72          Low                      9.8   

     Health_Issues  Occupation  Smoking  Alcohol_Consumption  
9995      Moderate  Healthcare        0                    1  
9996          Mild     Service        0                    0  
9997           NaN     Student        1                    1  
9998           NaN     Student        0                    0  
9999           NaN     Student        1                    0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       10000 non-null  int64  
 1   Age                      10000 non-null  int64  
 2   Gender                   10000 non-null  object 
 3   Country                  10000 non-null  object 
 4   Coffee_Intake            10000 non-null  float64
 5   Caffeine_mg              10000 non-null  float64
 6   Sleep_Hours              10000 non-null  float64
 7   Sleep_Quality            10000 non-null  object 
 8   BMI                      10000 non-null  float64
 9   Heart_Rate               10000 non-null  int64  
 10  Stress_Level             10000 non-null  object 
 11  Physical_Activity_Hours  10000 non-null  float64
 12  Health_Issues            4059 non-null   object 
 13  Occupation               10000 non-null  object 
 14  Smoking                

In [7]:
data.isna().sum()

ID                            0
Age                           0
Gender                        0
Country                       0
Coffee_Intake                 0
Caffeine_mg                   0
Sleep_Hours                   0
Sleep_Quality                 0
BMI                           0
Heart_Rate                    0
Stress_Level                  0
Physical_Activity_Hours       0
Health_Issues              5941
Occupation                    0
Smoking                       0
Alcohol_Consumption           0
dtype: int64

In [8]:
data["Sleep_Quality"].value_counts()

Sleep_Quality
Good         5637
Fair         2050
Excellent    1352
Poor          961
Name: count, dtype: int64

In [9]:
data.drop(columns=["Health_Issues","ID"],axis=1)

Age  Gender  Country  Coffee_Intake  Caffeine_mg  Sleep_Hours  \
0      40    Male  Germany            3.5        328.1          7.5   
1      33    Male  Germany            1.0         94.1          6.2   
2      42    Male   Brazil            5.3        503.7          5.9   
3      53    Male  Germany            2.6        249.2          7.3   
4      32  Female    Spain            3.1        298.0          5.3   
...   ...     ...      ...            ...          ...          ...   
9995   50  Female    Japan            2.1        199.8          6.0   
9996   18  Female       UK            3.4        319.2          5.8   
9997   26    Male    China            1.6        153.4          7.1   
9998   40  Female  Finland            3.4        327.1          7.0   
9999   42  Female   Brazil            2.9        277.5          6.4   

     Sleep_Quality   BMI  Heart_Rate Stress_Level  Physical_Activity_Hours  \
0             Good  24.9          78          Low                     14.5   
1             Good  20.0          67          Low                     11.0   
2             Fair  22.7          59       Medium                     11.2   
3             Good  24.7          71          Low                      6.6   
4             Fair  24.1          76       Medium                      8.5   
...            ...   ...         ...          ...                      ...   
9995          Fair  30.5          50       Medium                     10.1   
9996          Fair  19.1          71       Medium                     11.6   
9997          Good  25.1          66          Low                     13.7   
9998          Good  19.3          80          Low                      0.1   
9999          Good  28.1          72          Low                      9.8   

      Occupation  Smoking  Alcohol_Consumption  
0          Other        0                    0  
1        Service        0                    0  
2         Office        0                    0  
3          Other        0                    0  
4        Student        0                    1  
...          ...      ...                  ...  
9995  Healthcare        0                    1  
9996     Service        0                    0  
9997     Student        1                    1  
9998     Student        0                    0  
9999     Student        1                    0  

[10000 rows x 14 columns]

In [11]:
X=data.drop('Sleep_Quality',axis=1)
y=data['Sleep_Quality']

In [12]:
cat_features=X.select_dtypes(include=['object','category']).columns
X=pd.get_dummies(X,columns=cat_features,drop_first=True)

In [13]:
from sklearn.preprocessing import StandardScaler
num_features=X.select_dtypes(include=['int64','float64','bool']).columns
scaler=StandardScaler()
X[num_features]=scaler.fit_transform(X[num_features])

In [14]:
from sklearn.model_selection import train_test_split
X_temp,X_test,y_temp,y_test=train_test_split(X,y,test_size=0.15,random_state=42)
X_train,X_val,y_train,y_val=train_test_split(X_temp,y_temp,test_size=0.1176,random_state=42)

In [15]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(class_weight='balanced',random_state=42)
model.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [16]:
from sklearn.metrics import classification_report,accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
y_pred_val=model.predict(X_val)
y_pred_test=model.predict(X_test)

In [17]:
print("Validation Set Metrics:")
print(f"Accuracy:{accuracy_score(y_val,y_pred_val)*100:.4f}")
print(f"Precision:{precision_score(y_val,y_pred_val,average='weighted')*100:.4f}")
print(f"Recall:{recall_score(y_val,y_pred_val,average='weighted')*100:.4f}")
print(f"F1 Score:{f1_score(y_val,y_pred_val,average='weighted')*100:.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_val,y_pred_val))
print("\nClassification Report:")
print(classification_report(y_val,y_pred_val))

Validation Set Metrics:
Accuracy:98.5000
Precision:98.5656
Recall:98.5000
F1 Score:98.5165
Confusion Matrix:
[[141   0   3   0]
 [  0 209   0   0]
 [ 12   0 536   0]
 [  0   0   0  99]]

Classification Report:
              precision    recall  f1-score   support

   Excellent       0.92      0.98      0.95       144
        Fair       1.00      1.00      1.00       209
        Good       0.99      0.98      0.99       548
        Poor       1.00      1.00      1.00        99

    accuracy                           0.98      1000
   macro avg       0.98      0.99      0.98      1000
weighted avg       0.99      0.98      0.99      1000



In [18]:
print("Test Set Metrics:")
print(f"Accuracy:{accuracy_score(y_test,y_pred_test)*100:.4f}")
print(f"Precision:{precision_score(y_test,y_pred_test,average='weighted')*100:.4f}")
print(f"Recall:{recall_score(y_test,y_pred_test,average='weighted')*100:.4f}")
print(f"F1 Score:{f1_score(y_test,y_pred_test,average='weighted')*100:.4f}")
print("Confusion Matrix:")
print(confusion_matrix(y_test,y_pred_test))
print("\nClassification Report:")
print(classification_report(y_test,y_pred_test))

Test Set Metrics:
Accuracy:98.6667
Precision:98.6870
Recall:98.6667
F1 Score:98.6736
Confusion Matrix:
[[208   0   7   0]
 [  0 273   0   0]
 [ 13   0 866   0]
 [  0   0   0 133]]

Classification Report:
              precision    recall  f1-score   support

   Excellent       0.94      0.97      0.95       215
        Fair       1.00      1.00      1.00       273
        Good       0.99      0.99      0.99       879
        Poor       1.00      1.00      1.00       133

    accuracy                           0.99      1500
   macro avg       0.98      0.99      0.99      1500
weighted avg       0.99      0.99      0.99      1500

